In [2]:
import pandas as pd
import numpy as np
import time,os,sys,itertools
from collections import *

In [3]:
os.listdir()

['.git',
 '.gitignore',
 '.ipynb_checkpoints',
 'isolet1+2+3+4.data',
 'isolet5.data',
 'README.md',
 'shiftdataset.ipynb',
 'trimap-pytorch.ipynb',
 'tsne-sklearn.ipynb',
 'Untitled.ipynb']

In [7]:
data = pd.read_csv('isolet5.data',header = None)

In [9]:
data.describe()

,0,1,2,3,4,5,6,7,8,9,...,608,609,610,611,612,613,614,615,616,617
count,1559.000000,1559.000000,1559.000000,1559.000000,1559.000000,1559.000000,1559.000000,1559.000000,1559.000000,1559.000000,...,1559.000000,1559.000000,1559.000000,1559.000000,1559.000000,1559.000000,1559.000000,1559.000000,1559.000000,1559.000000
mean,-0.350661,0.137841,0.364133,0.471724,0.333729,0.166335,0.023048,-0.077981,-0.146737,-0.187881,...,0.377515,0.345729,0.344821,0.367918,0.321675,0.238712,0.209379,0.075183,-0.316846,13.500321
std,0.217239,0.310937,0.332451,0.308016,0.445074,0.561147,0.559272,0.533287,0.529293,0.520774,...,0.305946,0.308470,0.316957,0.318380,0.314528,0.322756,0.321861,0.318988,0.338601,7.504802
min,-0.900800,-0.597400,-0.517000,-0.822600,-0.887000,-1.000000,-0.996600,-0.972800,-0.983000,-1.000000,...,-0.803400,-0.653200,-0.514400,-0.607000,-0.487600,-0.619000,-0.627400,-0.771400,-0.960800,1.000000
25%,-0.503400,-0.093100,0.132400,0.252100,0.015200,-0.322800,-0.460700,-0.504900,-0.568500,-0.591200,...,0.156700,0.113500,0.117000,0.135200,0.081800,0.016200,-0.026000,-0.146500,-0.571400,7.000000
50%,-0.377600,0.106200,0.346600,0.475400,0.403400,0.175600,-0.048200,-0.167000,-0.259400,-0.279600,...,0.373200,0.341000,0.327200,0.354800,0.308600,0.214200,0.186800,0.039000,-0.367400,14.000000
75%,-0.212700,0.348500,0.607000,0.697500,0.678600,0.687200,0.510900,0.308500,0.199300,0.123400,...,0.604100,0.564900,0.586500,0.603100,0.548000,0.469100,0.428600,0.268800,-0.117900,20.000000
max,0.800000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.848000,26.000000

In [10]:
data.shape

(1559, 618)

In [12]:
data.iloc[:,-1]

0        1.0
1        1.0
2        2.0
3        2.0
4        3.0
5        3.0
6        4.0
7        4.0
8        5.0
9        5.0
10       6.0
11       6.0
12       7.0
13       7.0
14       8.0
15       8.0
16       9.0
17       9.0
18      10.0
19      10.0
20      11.0
21      11.0
22      12.0
23      12.0
24      13.0
25      13.0
26      14.0
27      14.0
28      15.0
29      15.0
        ...
1529    12.0
1530    12.0
1531    13.0
1532    13.0
1533    14.0
1534    14.0
1535    15.0
1536    15.0
1537    16.0
1538    16.0
1539    17.0
1540    17.0
1541    18.0
1542    18.0
1543    19.0
1544    19.0
1545    20.0
1546    20.0
1547    21.0
1548    21.0
1549    22.0
1550    22.0
1551    23.0
1552    23.0
1553    24.0
1554    24.0
1555    25.0
1556    25.0
1557    26.0
1558    26.0
Name: 617, Length: 1559, dtype: float64

In [13]:
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

In [15]:
X = data.iloc[:,:-2]
Y = data.iloc[:,-1]
X.shape,Y.shape

((1559, 616), (1559,))